### ISSUE TITLE
This could have been written in better way...

### ISSUE THREAD

**Issue by unixbhaskar** [ninjaaron/replacing-bash-scripting-with-python#5]
Well, while hovering through your stuff ...just stumbled over section "Using stdin, stdout..." in there one line could have been written in much better an concise way... like below

**the original line in your document:**

program-that-prints-something | grep 'a pattern'

**Should have been written like this below** 

grep "a pattern" program-that-prints-something 

Why? Because it gets rid of one process involved in it through piping. Very rudimentary but has a great impact, if you ever sit or work on a real-time server or production server.

I think it just slips in...you know it well.

**Comment by ninjaaron** [comment]
What you've suggested is not correct, or, it is not correct unless `program-that-prints-something` is the name of a file, in which case I would have had to use `cat`, and this would be a useless-use of cat.

I intended for `program-that-prints-something` to stand in for, well, the name of a program that prints something. :D

The other way to write what I've done in Bash would be `grep "a pattern" <(program-that-prints-something)`, which makes the output of a process look like a file argument. However, in the background bash is simply opening a fifo (i.e. a named pipe), so it's actually even more indirection, and it's going to block until the program finishes producing text.

Any time you connect the output of one process to the input of another, you are always using a pipe. The exception would be sending the output to an intermediary file first, but that's certainly not more concise.
