### ISSUE TITLE
Github Docs

### ISSUE THREAD

**Issue by JimScope** [ninjaaron/replacing-bash-scripting-with-python#8]
Consider moving it to github docs

**Comment by ninjaaron** [comment]
Might be a good idea. The thing I like about normal github repos is that I literally just have to write the document in markdown and github does the rendering, but I'll look at putting together a github docs frontend.

What are the benefits you see for using github docs?

**Comment by JimScope** [comment]
-Better integration with github services
-Centralization of documentary repos
And the best:
-A better view

**Comment by ivanhercaz** [comment]
@ninjaaron, are you planning to use GitHub Pages with `/docs` or to apply another system?
